### ISSUE TITLE
Cant get it to work on 1.8.0

### ISSUE THREAD

**Issue by Bitmasss** [heXeo/ubnt-fan-speed#1]
Hey, firstly, thanks for the script. It's exactly what I need right now.

That said, I can't get it to work correctly.

I see that it's just working for 1.7.2 but the latest version is 1.8.0 - is there anything specific needed for this version?

Thanks

**Comment by nekuz0r** [comment]
@Bitmasss Hello,

I am running it on 1.8.0 latest RC just fine. Can you tell me what's is not working for you exactly ?

Could you try the following simple steps ?
- scp my version of ubnt-fan-speed to your UDM Pro
- kill the currently running ubnt-fan-speed process
- run my version of ubnt-fan-speed

The new ubnt-fan-speed process will be running in foreground and the behaviour should be the same as the original.

**Comment by Bitmasss** [comment]
Ah, that's interesting. I just thought it was version specific.

Is there any other logs I can pull, or provide any more information?

I followed the steps and all seemed to go without an issue. The one thing I did notice is that /mnt/data didn't exist? The only folder that existed in /mnt/ was /mnt/persistent.

That also being said, these locations don't exist either: 

/usr/sbin/ubnt-fan-speed
/etc/ubnt/

Can you supply me your ubnt-fan-speed then please and I'll apply it? Thanks for replying.

**Comment by Bitmasss** [comment]
Actually, I've just realised I've been doing all this in the unifi-os shell....

Let me do it properly and let you know...

**Comment by Bitmasss** [comment]
Ok, everything works as intended now!
Sorry, I didnt realise where the scripts needed to be, but they're all working fine now.
Thanks for your help.
